# Generated by Django 5.0.2 on 2024-03-02 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='title',
            field=models.CharField(default='T-shirt Cut Copy', max_length=100),
            preserve_default=False,
        ),
    ]
