# Generated by Django 5.0.2 on 2024-03-02 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_band_like_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='like_new',
        ),
    ]
